In [2]:
import numpy as np
import scipy.stats as st
import matplotlib as mpl
import matplotlib.pyplot as plt
import os, math, sys


In [6]:
x = np.identity(2)
x[1,1] = np.inf
z = np.array([1,2,3,4])
zz = np.random.randint(0,3)
xx = list(range(5))
np.random.shuffle(xx)
print(xx)
print(xx.index(1))

[3, 0, 2, 1, 4]
3


In [4]:
for j in range(0,2):
    print(j)

0
1


In [49]:
nn = 1100000000
nm = np.inf
print(nn/nm)


0.0


In [47]:
zz = np.random.rand(3,3)*10
print(zz)
curInd = np.argmax(zz[:,0])
print(curInd)

[[7.83529144 9.0088345  0.10078056]
 [5.22967121 4.1022578  0.38401994]
 [1.94785961 9.83880988 5.74914831]]
0
