### Description: Student-t vs Gaussian

###### Author: Rimple Sandhu, Carleton University; Email: rimple_sandhu@outlook.com

In [30]:
#!/usr/bin/python
import numpy as np
import scipy.stats as st
import scipy.special as sc
import matplotlib.pyplot as plt
import os
import math
import sys

In [39]:
df = 5 # degree of freedom
mu = np.zeros((2,1)) # location parameter (mean of corrsponding gaussian)
sigma = np.identity(2)*3 # scale parameter (standard deviation of corresponding gaussian)
sigma[0,1] = 1
sigma[1,0] = 1
xx = np.ones((2,1))
xxd=[1]*2
print(mu,'\n',sigma)
print(np.matmul(mud,xx))

[[0.]
 [0.]] 
 [[3. 1.]
 [1. 3.]]
[4.]


In [40]:
#Xgrid = linspace(mu-6*sigma,mu+6*sigma,100)
#Xgrid = linspace(0.01,mu+6*sigma,100)
Xtdist = st.t(df,np.transpose(mu),sigma)
Xgdist = st.norm(mu,sigma)
print('Gaussian:  ',*Xgdist.stats(moments='mv'))
print('Student-t: ',*Xtdist.stats(moments='mv'))
st.t.pdf(xx,df,mu,sigma)

Gaussian:   [[0. 0.]
 [0. 0.]] [[9. 1.]
 [1. 9.]]
Student-t:  [[0. 0.]
 [0. 0.]] [[15.          1.66666667]
 [ 1.66666667 15.        ]]


array([[0.11846134, 0.2196798 ],
       [0.2196798 , 0.11846134]])

In [44]:
def mymvtdist(x, mu, df, Sigma):
    x = np.atleast_2d(x) # requires x as 2d
    print(x,mu)
    nD = Sigma.shape[0] # dimensionality
    numerator = sc.gamma(1.0 * (nD + df) / 2.0)
    denominator = (np.exp(sc.gammaln(1.0*df/2.0))*np.power(df*np.pi,1.0*nD/2.0)*
                   np.power(np.linalg.det(Sigma),1.0/2.0)*np.power(1.0+(1.0/df)*
                   np.diagonal(np.dot(np.dot((x-mu).T,np.linalg.inv(Sigma)),x-mu)),1.0*(nD + df)/2.0))
    return 1.0*numerator/denominator

In [45]:
mymvtdist(xx,mu,df,sigma)

[[1.]
 [1.]] [[0.]
 [0.]]


array([0.04030888])

In [43]:
t.pdf(5,1000,5,2)

NameError: name 't' is not defined